[build]
  publish = "dist/frontend/browser"
  command = "ng build --configuration production"

[[redirects]]
  from = "/"
  to = "/connexion"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
